version: "3.9"
services:
    sqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
        - '1433:1433'
        environment:
            SA_PASSWORD: "YOUR_STRONG_PASSWORD_HERE_123"
            ACCEPT_EULA: "Y"
        volumes:
        - './drive:/var/opt/mssql'